"""initial codepilot schema

Revision ID: 1e1cbdae8e3b
Revises:
Create Date: 2026-09-13 18:26:20.444857

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1e1cbdae8e3b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_agent',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('card_version', sa.String(length=16), nullable=False),
    sa.Column('protocol_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_schema', sa.String(length=128), nullable=False),
    sa.Column('output_schemas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('auth_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('card_hash', sa.String(length=80), nullable=False),
    sa.Column('card_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'card_version', name='uq_a2a_agent_card_version')
    )
    op.create_index(op.f('ix_a2a_agent_agent_id'), 'a2a_agent', ['agent_id'], unique=False)
    op.create_index(op.f('ix_a2a_agent_created_at'), 'a2a_agent', ['created_at'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_index('ix_audit_event_task', 'audit_event', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_audit_event_trace', 'audit_event', ['trace_id', 'created_at'], unique=False)
    op.create_table('eval_case',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset', 'case_id', name='uq_eval_case')
    )
    op.create_table('eval_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('modes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('runs_per_case', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report_ref', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('command_type', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('input_hash', sa.String(length=80), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('input_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('base_commit', sa.String(length=128), nullable=False),
    sa.Column('context_policy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('needs_human_from', sa.String(length=24), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('budget_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pending', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('child_tasks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fixed_comment_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active_patch_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'REVIEWING', 'REVIEWED', 'FIXING', 'TESTING', 'PENDING_APPROVAL', 'MERGED', 'NEEDS_HUMAN', 'REJECTED', 'FAILED')", name='ck_review_task_status'),
    sa.CheckConstraint('state_version >= 1', name='ck_review_task_state_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'command_type', 'idempotency_key', name='uq_review_task_idempotency')
    )
    op.create_index(op.f('ix_review_task_created_at'), 'review_task', ['created_at'], unique=False)
    op.create_index('ix_review_task_input_hash', 'review_task', ['input_hash'], unique=False)
    op.create_index('ix_review_task_parent_state', 'review_task', ['status', 'state_version'], unique=False)
    op.create_index(op.f('ix_review_task_trace_id'), 'review_task', ['trace_id'], unique=False)
    op.create_table('tool_execution',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.String(length=16), nullable=False),
    sa.Column('access', sa.String(length=8), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('denied_reason', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('params_hash', sa.String(length=80), nullable=False),
    sa.Column('result_hash', sa.String(length=80), nullable=True),
    sa.Column('result_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_ref', sa.String(length=512), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'agent_id', 'tool_name', 'idempotency_key', name='uq_tool_execution_idempotency')
    )
    op.create_index(op.f('ix_tool_execution_created_at'), 'tool_execution', ['created_at'], unique=False)
    op.create_index('ix_tool_execution_task', 'tool_execution', ['task_id', 'created_at'], unique=False)
    op.create_table('a2a_task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('protocol_version', sa.String(length=8), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('input_artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_output_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.String(length=256), nullable=True),
    sa.Column('event_cursor', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'working', 'input_required', 'completed', 'failed', 'canceled')", name='ck_a2a_task_status'),
    sa.CheckConstraint('attempt >= 1 AND attempt <= 2', name='ck_a2a_task_attempt'),
    sa.CheckConstraint('state_version >= 1', name='ck_a2a_task_state_version'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_task_id', 'agent_id', 'task_type', 'idempotency_key', name='uq_a2a_task_idempotency')
    )
    op.create_index(op.f('ix_a2a_task_created_at'), 'a2a_task', ['created_at'], unique=False)
    op.create_index('ix_a2a_task_parent', 'a2a_task', ['parent_task_id'], unique=False)
    op.create_index('ix_a2a_task_status_deadline', 'a2a_task', ['status', 'deadline'], unique=False)
    op.create_index(op.f('ix_a2a_task_trace_id'), 'a2a_task', ['trace_id'], unique=False)
    op.create_table('eval_result',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('review_task_id', sa.String(length=64), nullable=True),
    sa.Column('finding_recall', sa.Float(), nullable=True),
    sa.Column('finding_precision', sa.Float(), nullable=True),
    sa.Column('patch_valid', sa.Boolean(), nullable=True),
    sa.Column('verify_passed', sa.Boolean(), nullable=True),
    sa.Column('route_correct', sa.Boolean(), nullable=True),
    sa.Column('artifact_schema_ok', sa.Boolean(), nullable=True),
    sa.Column('task_converged', sa.Boolean(), nullable=True),
    sa.Column('trace_complete', sa.Boolean(), nullable=True),
    sa.Column('recovery_stable', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('injected_fault', sa.String(length=64), nullable=True),
    sa.Column('recovery_action', sa.String(length=128), nullable=True),
    sa.Column('security_invariants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['eval_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', 'mode', 'run_index', name='uq_eval_result')
    )
    op.create_index('ix_eval_result_run', 'eval_result', ['run_id'], unique=False)
    op.create_table('fix_patch',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('patch_version', sa.Integer(), nullable=False),
    sa.Column('patch_hash', sa.String(length=80), nullable=False),
    sa.Column('base_commit', sa.String(length=128), nullable=False),
    sa.Column('target_branch', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fix_category', sa.String(length=32), nullable=False),
    sa.Column('finding_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changed_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changed_functions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('added_lines', sa.Integer(), nullable=False),
    sa.Column('removed_lines', sa.Integer(), nullable=False),
    sa.Column('scope_drift', sa.Boolean(), nullable=False),
    sa.Column('scope_drift_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('wide_impact', sa.Boolean(), nullable=False),
    sa.Column('coverage_before', sa.Float(), nullable=True),
    sa.Column('coverage_after', sa.Float(), nullable=True),
    sa.Column('coverage_delta', sa.Float(), nullable=True),
    sa.Column('test_gap', sa.Boolean(), nullable=False),
    sa.Column('sandbox_run_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('candidate', 'rejected', 'verified', 'pending_approval', 'approved', 'applied', 'rolled_back')", name='ck_fix_patch_status'),
    sa.CheckConstraint('patch_version >= 1', name='ck_fix_patch_version_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'idempotency_key', name='uq_fix_patch_idempotency'),
    sa.UniqueConstraint('task_id', 'patch_version', name='uq_fix_patch_version')
    )
    op.create_index(op.f('ix_fix_patch_created_at'), 'fix_patch', ['created_at'], unique=False)
    op.create_index(op.f('ix_fix_patch_task_id'), 'fix_patch', ['task_id'], unique=False)
    op.create_table('review_comment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('finding_id', sa.String(length=256), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('cwe', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('auto_fixable', sa.Boolean(), nullable=False),
    sa.Column('fix_category', sa.String(length=32), nullable=True),
    sa.Column('impact_scope', sa.String(length=512), nullable=False),
    sa.Column('call_graph_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('critical', 'warning', 'info')", name='ck_review_comment_severity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_review_comment_confidence'),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'file', 'line', 'rule_id', name='uq_review_comment_dedup')
    )
    op.create_index(op.f('ix_review_comment_created_at'), 'review_comment', ['created_at'], unique=False)
    op.create_index('ix_review_comment_task', 'review_comment', ['task_id'], unique=False)
    op.create_table('a2a_artifact',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_ref', sa.String(length=512), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['a2a_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'artifact_type', 'content_hash', name='uq_a2a_artifact_content')
    )
    op.create_index(op.f('ix_a2a_artifact_created_at'), 'a2a_artifact', ['created_at'], unique=False)
    op.create_index(op.f('ix_a2a_artifact_parent_task_id'), 'a2a_artifact', ['parent_task_id'], unique=False)
    op.create_index('ix_a2a_artifact_task', 'a2a_artifact', ['task_id'], unique=False)
    op.create_table('a2a_message',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=80), nullable=False),
    sa.Column('payload_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['a2a_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_message_created_at'), 'a2a_message', ['created_at'], unique=False)
    op.create_index('ix_a2a_message_task', 'a2a_message', ['task_id', 'created_at'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('patch_id', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('decided_role', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('patch_version', sa.Integer(), nullable=False),
    sa.Column('patch_hash', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('approve', 'reject')", name='ck_approval_decision'),
    sa.ForeignKeyConstraint(['patch_id'], ['fix_patch.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'patch_version', name='uq_approval_patch_version')
    )
    op.create_index(op.f('ix_approval_created_at'), 'approval', ['created_at'], unique=False)
    op.create_index('ix_approval_task', 'approval', ['task_id'], unique=False)
    op.create_table('sandbox_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('patch_id', sa.String(length=64), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.String(length=256), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('disk_limit_mb', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('coverage_before', sa.Float(), nullable=True),
    sa.Column('coverage_after', sa.Float(), nullable=True),
    sa.Column('coverage_delta', sa.Float(), nullable=True),
    sa.Column('resource_usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stdout_sanitized', sa.Text(), nullable=False),
    sa.Column('stderr_sanitized', sa.Text(), nullable=False),
    sa.Column('test_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'passed', 'failed', 'timeout', 'resource_exceeded', 'error')", name='ck_sandbox_run_status'),
    sa.ForeignKeyConstraint(['patch_id'], ['fix_patch.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_run_created_at'), 'sandbox_run', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_run_created_at'), table_name='sandbox_run')
    op.drop_table('sandbox_run')
    op.drop_index('ix_approval_task', table_name='approval')
    op.drop_index(op.f('ix_approval_created_at'), table_name='approval')
    op.drop_table('approval')
    op.drop_index('ix_a2a_message_task', table_name='a2a_message')
    op.drop_index(op.f('ix_a2a_message_created_at'), table_name='a2a_message')
    op.drop_table('a2a_message')
    op.drop_index('ix_a2a_artifact_task', table_name='a2a_artifact')
    op.drop_index(op.f('ix_a2a_artifact_parent_task_id'), table_name='a2a_artifact')
    op.drop_index(op.f('ix_a2a_artifact_created_at'), table_name='a2a_artifact')
    op.drop_table('a2a_artifact')
    op.drop_index('ix_review_comment_task', table_name='review_comment')
    op.drop_index(op.f('ix_review_comment_created_at'), table_name='review_comment')
    op.drop_table('review_comment')
    op.drop_index(op.f('ix_fix_patch_task_id'), table_name='fix_patch')
    op.drop_index(op.f('ix_fix_patch_created_at'), table_name='fix_patch')
    op.drop_table('fix_patch')
    op.drop_index('ix_eval_result_run', table_name='eval_result')
    op.drop_table('eval_result')
    op.drop_index(op.f('ix_a2a_task_trace_id'), table_name='a2a_task')
    op.drop_index('ix_a2a_task_status_deadline', table_name='a2a_task')
    op.drop_index('ix_a2a_task_parent', table_name='a2a_task')
    op.drop_index(op.f('ix_a2a_task_created_at'), table_name='a2a_task')
    op.drop_table('a2a_task')
    op.drop_index('ix_tool_execution_task', table_name='tool_execution')
    op.drop_index(op.f('ix_tool_execution_created_at'), table_name='tool_execution')
    op.drop_table('tool_execution')
    op.drop_index(op.f('ix_review_task_trace_id'), table_name='review_task')
    op.drop_index('ix_review_task_parent_state', table_name='review_task')
    op.drop_index('ix_review_task_input_hash', table_name='review_task')
    op.drop_index(op.f('ix_review_task_created_at'), table_name='review_task')
    op.drop_table('review_task')
    op.drop_table('eval_run')
    op.drop_table('eval_case')
    op.drop_index('ix_audit_event_trace', table_name='audit_event')
    op.drop_index('ix_audit_event_task', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_a2a_agent_created_at'), table_name='a2a_agent')
    op.drop_index(op.f('ix_a2a_agent_agent_id'), table_name='a2a_agent')
    op.drop_table('a2a_agent')
    # ### end Alembic commands ###
